### ISSUE TITLE
Is the `.dapprc` file necessary anymore?

### ISSUE THREAD

**Issue by PaulRBerg** [cleanunicorn/ethereum-smartcontract-template#11]
Since v0.2, Foundry has switched to their own configuration file `foundry.toml`.

Is the [.dapprc](https://github.com/cleanunicorn/ethereum-smartcontract-template/blob/5eed472f974e7eba69ad4b5e0bfe042670b657e5/.dapprc) file necessary anymore?

Side note: I would have opened a [discussion](https://docs.github.com/en/discussions) for this instead of a GitHub issue, but they have to be manually enabled first.

**Comment by cleanunicorn** [comment]
Thank you for the bump. I enabled discussions.

I will remove the `.dapprrc` file.
